/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project1;

import java.io.FileWriter;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author HP
 */
public class Discount extends javax.swing.JFrame {
    /**
     * Creates new form Discount
     */
   public static  CircularDoublyLinkedList list=new CircularDoublyLinkedList();
    public Discount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 234, -1, -1));

        jButton1.setText("GET DISCOUNT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 120, 30));

        jTextArea2.setColumns(5);
        jTextArea2.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 140, 150));

        jButton2.setText("NEXT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/DiscountNN.PNG"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    Verify obj=new Verify();
    String discountVar="";
    if (obj.counter<3 && obj.counter2==0){
        setText();
        int Random=(int)(Math.random()*10);
          list.temp=list.head;
            for (int i=0;i<=Random;i++){
                
                discountVar=list.temp.data;
                list.temp=list.temp.next;
            }
            jTextArea2.setText("Congrats! You have "+ System.lineSeparator() +"got "+ discountVar + " % Discount" + System.lineSeparator() + "on your Ride...");
       try {
           AppendFile(jTextArea2.getText());
       } catch (IOException ex) {
           Logger.getLogger(Discount.class.getName()).log(Level.SEVERE, null, ex);
       }
       obj.counter2=obj.counter2 +1;
    }
    else {
  jTextArea2.setText(discountVar);
  JOptionPane.showMessageDialog(rootPane,"You have already got the discount.Please Click on the NEXT Button"); 
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       new  Verify().setVisible(true);
              this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
     
    public void AppendFile(String s) throws IOException{
        Verify Obj=new Verify();
        BufferedReader reader;
        if (Obj.counter==0){
        reader=new BufferedReader(new FileReader("Verfication1.txt"));
        String line;
      while ((line = reader.readLine()) !=null) {
       
      }
           File file=new File("Verfication1.txt");
           FileWriter filewriter=new FileWriter(file,true);
           BufferedWriter buffer=new BufferedWriter(filewriter);
           PrintWriter printwriter = new PrintWriter(buffer);
           printwriter.println(s);
           printwriter.close();
           buffer.close();
           reader.close();
        }
         if (Obj.counter==1){
          reader=new BufferedReader(new FileReader("Verfication2.txt"));
        String line;
      while ((line = reader.readLine()) !=null) {
       
      }
           File file=new File("Verfication2.txt");
           FileWriter filewriter=new FileWriter(file,true);
           BufferedWriter buffer=new BufferedWriter(filewriter);
           PrintWriter printwriter = new PrintWriter(buffer);
           printwriter.println(s);
           printwriter.close();
           buffer.close();
           reader.close();
    }
          if (Obj.counter==2){
           reader=new BufferedReader(new FileReader("Verfication3.txt"));
        String line;
      while ((line = reader.readLine()) !=null) {
       
      }
           File file=new File("Verfication3.txt");
           FileWriter filewriter=new FileWriter(file,true);
           BufferedWriter buffer=new BufferedWriter(filewriter);
           PrintWriter printwriter = new PrintWriter(buffer);
           printwriter.println(s);
           printwriter.close();
           buffer.close();
           reader.close();
    }
    }
    public static void main(String args[]) {
       
      
        
        
     
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Discount().setVisible(true);
           
            }
        });
       
    }
     public void setText(){
     list.addLast("1");
     list.addLast("2");
     list.addLast("3");
     list.addLast("4");
     list.addLast("5");
     list.addLast("6");
     list.addLast("7");
     list.addLast("8");
     list.addLast("9");
     list.addLast("10");
         /* GetDiscount.setText("1");
         String discountVar="";
         int Random=(int)Math.random()*10;
            for (int i=0;i<Random;i++){
                TextArea.setText(list.head.next.data);
                discountVar=TextArea.getText();
            }
            GetDiscount.setText("Congrats! You have got" + discountVar + "% discount on your Ride.....");
        */}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
