/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project1;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Page4 extends javax.swing.JFrame {

    /**
     * Creates new form Page4
     */
    public Page4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Delux = new javax.swing.JRadioButton();
        Premium = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Time = new javax.swing.JTextField();
        AM = new javax.swing.JRadioButton();
        PM = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        Airport = new javax.swing.JRadioButton();
        Gulshan = new javax.swing.JRadioButton();
        Clifton = new javax.swing.JRadioButton();
        Bahadurabad = new javax.swing.JRadioButton();
        Airport2 = new javax.swing.JRadioButton();
        Gulshan2 = new javax.swing.JRadioButton();
        Clifton2 = new javax.swing.JRadioButton();
        Bahadurabad2 = new javax.swing.JRadioButton();
        Civic = new javax.swing.JCheckBox();
        Carolla = new javax.swing.JCheckBox();
        BMW = new javax.swing.JCheckBox();
        Mercedes = new javax.swing.JCheckBox();
        Check1 = new javax.swing.JLabel();
        Check2 = new javax.swing.JLabel();
        SaveL = new javax.swing.JButton();
        Check3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Check4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Delux.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Delux.setForeground(new java.awt.Color(255, 255, 255));
        Delux.setText("Deluxe Cars");
        Delux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeluxActionPerformed(evt);
            }
        });
        getContentPane().add(Delux, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        Premium.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Premium.setForeground(new java.awt.Color(255, 255, 255));
        Premium.setText("Premium Cars");
        Premium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PremiumActionPerformed(evt);
            }
        });
        getContentPane().add(Premium, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PickUp Location");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DropOff Location");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("BOOK IT!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, -1, 30));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enter your PickUp time:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 180, 20));

        Time.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimeActionPerformed(evt);
            }
        });
        getContentPane().add(Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 120, -1));

        AM.setForeground(new java.awt.Color(255, 255, 255));
        AM.setText("AM");
        AM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AMActionPerformed(evt);
            }
        });
        getContentPane().add(AM, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 40, -1));

        PM.setForeground(new java.awt.Color(255, 255, 255));
        PM.setText("PM");
        PM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PMActionPerformed(evt);
            }
        });
        getContentPane().add(PM, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("KARPOOL BOOKING SYSTEM");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 40));

        Airport.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Airport.setForeground(new java.awt.Color(255, 255, 255));
        Airport.setText("AIRPORT");
        Airport.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Airport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AirportActionPerformed(evt);
            }
        });
        getContentPane().add(Airport, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        Gulshan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Gulshan.setForeground(new java.awt.Color(255, 255, 255));
        Gulshan.setText("GULSHAN");
        Gulshan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Gulshan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GulshanActionPerformed(evt);
            }
        });
        getContentPane().add(Gulshan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 100, -1));

        Clifton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Clifton.setForeground(new java.awt.Color(255, 255, 255));
        Clifton.setText("CLIFTON");
        Clifton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Clifton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CliftonActionPerformed(evt);
            }
        });
        getContentPane().add(Clifton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 100, -1));

        Bahadurabad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Bahadurabad.setForeground(new java.awt.Color(255, 255, 255));
        Bahadurabad.setText("BAHADURABAD");
        Bahadurabad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Bahadurabad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BahadurabadActionPerformed(evt);
            }
        });
        getContentPane().add(Bahadurabad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        Airport2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Airport2.setForeground(new java.awt.Color(255, 255, 255));
        Airport2.setText("AIRPORT");
        Airport2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Airport2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Airport2ActionPerformed(evt);
            }
        });
        getContentPane().add(Airport2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, -1, -1));

        Gulshan2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Gulshan2.setForeground(new java.awt.Color(255, 255, 255));
        Gulshan2.setText("GULSHAN");
        Gulshan2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Gulshan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gulshan2ActionPerformed(evt);
            }
        });
        getContentPane().add(Gulshan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, -1, -1));

        Clifton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Clifton2.setForeground(new java.awt.Color(255, 255, 255));
        Clifton2.setText("CLIFTON");
        Clifton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Clifton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clifton2ActionPerformed(evt);
            }
        });
        getContentPane().add(Clifton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        Bahadurabad2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Bahadurabad2.setForeground(new java.awt.Color(255, 255, 255));
        Bahadurabad2.setText("BAHADURABAD");
        Bahadurabad2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Bahadurabad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bahadurabad2ActionPerformed(evt);
            }
        });
        getContentPane().add(Bahadurabad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, -1));

        Civic.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Civic.setForeground(new java.awt.Color(255, 255, 255));
        Civic.setText("CIVIC");
        Civic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CivicActionPerformed(evt);
            }
        });
        getContentPane().add(Civic, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 100, -1));

        Carolla.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Carolla.setForeground(new java.awt.Color(255, 255, 255));
        Carolla.setText("CAROLLA");
        Carolla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarollaActionPerformed(evt);
            }
        });
        getContentPane().add(Carolla, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        BMW.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BMW.setForeground(new java.awt.Color(255, 255, 255));
        BMW.setText("BMW");
        BMW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMWActionPerformed(evt);
            }
        });
        getContentPane().add(BMW, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, -1, -1));

        Mercedes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Mercedes.setForeground(new java.awt.Color(255, 255, 255));
        Mercedes.setText("MERCEDES");
        Mercedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MercedesActionPerformed(evt);
            }
        });
        getContentPane().add(Mercedes, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, -1, -1));

        Check1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Check1.setForeground(new java.awt.Color(255, 255, 255));
        Check1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                Check1ComponentRemoved(evt);
            }
        });
        getContentPane().add(Check1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 140, 20));

        Check2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Check2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Check2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 140, 20));

        SaveL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SaveL.setText("Save Location details!");
        SaveL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveLActionPerformed(evt);
            }
        });
        getContentPane().add(SaveL, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 230, -1));

        Check3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Check3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Check3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 150, 20));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, -1, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 70, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/xoxo (1).png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));
        getContentPane().add(Check4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, 80, 20));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean isOk=true;
        PrintWriter outFile=null;
          if(saveL.equals(" ") ==false) {
            if((Check1.getText().equals("")==true) || (Check2.getText().equals("")==true)){ 
                JOptionPane.showMessageDialog(rootPane,"Please Select Your Locations First!");
                isOk=false;
            }   String c=Check3.getText();
            
            if(c.equals("Deluxe Selected")==true) {
                DeluxePrice deluxe=new DeluxePrice(Check1.getText(),Check2.getText());
                System.out.println(deluxe.calculate());
            }   if(c.equals("Premium Selected")==true) {
                PremiumPrice obj2=new PremiumPrice(Check1.getText(),Check2.getText());
                System.out.println(obj2.calculate2());
            }
            else if(c.equals("")==true) {
                JOptionPane.showMessageDialog(rootPane,"Error,Please Select The Requirments!");
                isOk=false;
            }  
           
             
            if(Check4.getText().equals("CIVIC")==true) {
                Civic obj1= new Civic();
               String C= obj1.toString();
               
            try {
                 DeluxePrice price1=new DeluxePrice(Check1.getText(),Check2.getText());
                
                obj1.Filing(C,price1.getPick(),price1.getDrop(),price1.calculate());
                
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Page4.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
            if(Check4.getText().equals("CAROLLA")==true) {
                Carolla obj= new Carolla();
               String D= obj.toString();
            try {
                DeluxePrice price2=new DeluxePrice(Check1.getText(),Check2.getText());
                obj.Filing(D,price2.getPick(),price2.getDrop(),price2.calculate());
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Page4.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
            if(Check4.getText().equals("BMW")==true) {
                BMW obj3= new BMW();
               String E= obj3.toString();
            try {
                PremiumPrice price3=new PremiumPrice(Check1.getText(),Check2.getText());
                obj3.Filing(E,price3.getPick(),price3.getDrop(),price3.calculate2());
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Page4.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
            if(Check4.getText().equals("MERCEDES")==true) {
                Mercedes obj4= new Mercedes();
               String C= obj4.toString();
            try {
                PremiumPrice price4=new PremiumPrice(Check1.getText(),Check2.getText());
                obj4.Filing(C,price4.getPick(),price4.getDrop(),price4.calculate2());
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Page4.class.getName()).log(Level.SEVERE, null, ex);
            }        
    }//GEN-LAST:event_jButton1ActionPerformed
    }
    if(saveL.equals(" ") ==true) {
               JOptionPane.showMessageDialog(rootPane,"Please Select Your Locations and Click On Save Location Details!");
               isOk=false;
          }
    if (isOk==true){
    new  Discount().setVisible(true);
              this.setVisible(false);
      }
    }
    private void TimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TimeActionPerformed

    private void Bahadurabad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bahadurabad2ActionPerformed
        Airport2.setSelected(false);
        Gulshan2.setSelected(false);
         Clifton2.setSelected(false);
         Bahadurabad.setSelected(false);
          Check2.setText("Bahadurabad");
    }//GEN-LAST:event_Bahadurabad2ActionPerformed

    private void CivicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CivicActionPerformed
       Carolla.setSelected(false);
       BMW.setSelected(false);
       Mercedes.setSelected(false);
       Delux.setSelected(true);
       Premium.setSelected(false);
       Check3.setText("Deluxe Selected");
      Check4.setText(Civic.getText());
       
    }//GEN-LAST:event_CivicActionPerformed

    private void CliftonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CliftonActionPerformed
         Airport.setSelected(false);
        Gulshan.setSelected(false);
         Bahadurabad.setSelected(false);
         Clifton2.setSelected(false);
          Check1.setText("Clifton");
          
    }//GEN-LAST:event_CliftonActionPerformed

    private void AirportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AirportActionPerformed
       Gulshan.setSelected(false);
        Clifton.setSelected(false);
         Bahadurabad.setSelected(false);
         Airport2.setSelected(false);
         Check1.setText("Airport");
    }//GEN-LAST:event_AirportActionPerformed

    private void GulshanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GulshanActionPerformed
        Airport.setSelected(false);
        Clifton.setSelected(false);
         Bahadurabad.setSelected(false);
         Gulshan2.setSelected(false);
          Check1.setText("Gulshan");
    }//GEN-LAST:event_GulshanActionPerformed

    private void BahadurabadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BahadurabadActionPerformed
        Airport.setSelected(false);
        Gulshan.setSelected(false);
         Clifton.setSelected(false);
         Bahadurabad2.setSelected(false);
          Check1.setText("Bahadurabad");
    }//GEN-LAST:event_BahadurabadActionPerformed

    private void Airport2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Airport2ActionPerformed
         Gulshan2.setSelected(false);
        Clifton2.setSelected(false);
         Bahadurabad2.setSelected(false);
         Airport.setSelected(false);
         Check2.setText("Airport");
    }//GEN-LAST:event_Airport2ActionPerformed

    private void Gulshan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gulshan2ActionPerformed
         Airport2.setSelected(false);
        Clifton2.setSelected(false);
         Bahadurabad2.setSelected(false);
         Gulshan.setSelected(false);
          Check2.setText("Gulshan");
    }//GEN-LAST:event_Gulshan2ActionPerformed

    private void Clifton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clifton2ActionPerformed
         Airport2.setSelected(false);
        Gulshan2.setSelected(false);
         Bahadurabad2.setSelected(false);
         Clifton.setSelected(false);
          Check2.setText("Clifton");
    }//GEN-LAST:event_Clifton2ActionPerformed

    private void DeluxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeluxActionPerformed
         Premium.setSelected(false);
         BMW.setSelected(false);
         Mercedes.setSelected(false);
         
         
        
        
    }//GEN-LAST:event_DeluxActionPerformed

    private void PremiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PremiumActionPerformed
       Delux.setSelected(false);
       Civic.setSelected(false);
       Carolla.setSelected(false);
       
        
    }//GEN-LAST:event_PremiumActionPerformed

    private void CarollaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarollaActionPerformed
     Civic.setSelected(false);
       BMW.setSelected(false);
       Mercedes.setSelected(false);
       Delux.setSelected(true);
       Premium.setSelected(false);
       Check3.setText("Deluxe Selected");
       Check4.setText(Carolla.getText());
    }//GEN-LAST:event_CarollaActionPerformed

    private void BMWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMWActionPerformed
        Mercedes.setSelected(false);
       Civic.setSelected(false);
       Carolla.setSelected(false);
       Premium.setSelected(true);
       Delux.setSelected(false);
       Check3.setText("Premium Selected");
       Check4.setText(BMW.getText());
    }//GEN-LAST:event_BMWActionPerformed

    private void MercedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MercedesActionPerformed
    BMW.setSelected(false);
       Civic.setSelected(false);
       Carolla.setSelected(false);
       Premium.setSelected(true);
       Delux.setSelected(false);
       Check3.setText("Premium Selected");
       Check4.setText(Mercedes.getText());
    }//GEN-LAST:event_MercedesActionPerformed

    private void Check1ComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_Check1ComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_Check1ComponentRemoved

    private void SaveLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveLActionPerformed
     saveL="done";
     String a=Check1.getText();
     String b=Check2.getText();
     if(a.equals(b)==true){
         JOptionPane.showMessageDialog(rootPane,"Error, Please Recheck Your Location!");
         Check1.setText("");
         Check2.setText("");
         Airport.setSelected(false);
         Gulshan.setSelected(false);
         Clifton.setSelected(false);
         Bahadurabad.setSelected(false);
         Airport2.setSelected(false);
         Gulshan2.setSelected(false);
         Clifton2.setSelected(false);
         Bahadurabad2.setSelected(false);  
     }
    }//GEN-LAST:event_SaveLActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       Airport.setSelected(false);
         Gulshan.setSelected(false);
         Clifton.setSelected(false);
         Bahadurabad.setSelected(false);
         Airport2.setSelected(false);
         Gulshan2.setSelected(false);
         Clifton2.setSelected(false);
         Bahadurabad2.setSelected(false);   
         AM.setSelected(false);
         PM.setSelected(false);
         Delux.setSelected(false);
         Premium.setSelected(false);
         Civic.setSelected(false);
         Carolla.setSelected(false);
         BMW.setSelected(false);
         Mercedes.setSelected(false);   
         Check1.setText("");
         Check2.setText("");
         Check3.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void AMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AMActionPerformed
       PM.setSelected(false);
    }//GEN-LAST:event_AMActionPerformed

    private void PMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PMActionPerformed
       AM.setSelected(false);
    }//GEN-LAST:event_PMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Page4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Page4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Page4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Page4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Page4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AM;
    private javax.swing.JRadioButton Airport;
    private javax.swing.JRadioButton Airport2;
    private javax.swing.JCheckBox BMW;
    private javax.swing.JRadioButton Bahadurabad;
    private javax.swing.JRadioButton Bahadurabad2;
    private javax.swing.JCheckBox Carolla;
    private javax.swing.JLabel Check1;
    private javax.swing.JLabel Check2;
    private javax.swing.JLabel Check3;
    private javax.swing.JLabel Check4;
    private javax.swing.JCheckBox Civic;
    private javax.swing.JRadioButton Clifton;
    private javax.swing.JRadioButton Clifton2;
    private javax.swing.JRadioButton Delux;
    private javax.swing.JRadioButton Gulshan;
    private javax.swing.JRadioButton Gulshan2;
    private javax.swing.JCheckBox Mercedes;
    private javax.swing.JRadioButton PM;
    private javax.swing.JRadioButton Premium;
    private javax.swing.JButton SaveL;
    private javax.swing.JTextField Time;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
public String saveL=" ";
}
 
